### ISSUE TITLE
missing hardcoded file

### ISSUE THREAD

**Issue by arnounesco** [iodepo/oih-ui#9]
./indexer.py 
Traceback (most recent call last):
  File "/Users/arno/PhpstormProjects/oih-ui/indexer/./indexer.py", line 424, in <module>
    index_all(['../all_files.v2.txt'])
  File "/Users/arno/PhpstormProjects/oih-ui/indexer/./indexer.py", line 344, in index_all
    with open(path) as files:
FileNotFoundError: [Errno 2] No such file or directory: '../all_files.v2.txt'

**Comment by arnounesco** [comment]
seems like the hardcoded files are gone
